#!/bin/bash

declare -A morse
morse[a]=".- "
morse[b]="-... "
morse[c]="-.-. "
morse[d]="-.. "
morse[e]=". "
morse[f]="..-. "
morse[g]="--. "
morse[h]=".... "
morse[i]=".. "
morse[j]=".--- "
morse[k]="-.- "
morse[l]=".-.. "
morse[m]="-- "
morse[n]="-. "
morse[o]="--- "
morse[p]=".--. "
morse[q]="--.- "
morse[r]=".-. "
morse[s]="... "
morse[t]="- "
morse[u]="..- "
morse[v]="...- "
morse[w]=".-- "
morse[x]="-..- "
morse[y]="-.-- "
morse[z]="--.. "
morse[" "]="_"

br="/sys/class/leds/input*::capslock/brightness"

text=$*

echo "Starting!"
sleep 1
for i in $(seq 1 ${#text}); do
    letr="${text:i-1:1}"
    echo "$letr: ${morse[$letr]}"
    for j in $(seq 1 ${#morse[$letr]}); do
        smth="${morse[$letr]:j-1:1}"
        case "$smth" in
            ".")
                echo "1" > $br
                sleep 0.5
                echo "0" > $br
                sleep 0.5;;
            "-")
                echo "1" > $br
                sleep 1.5
                echo "0" > $br
                sleep 0.5;;
            "_") sleep 1.5;;
        esac
    done
done
